import type { Metadata } from 'next';
import { Section } from '@/components/layout/section';
import { FadeInOnScroll } from '@/components/motion/fade-in-on-scroll';

export const metadata: Metadata = {
  title: 'Terms of Service — PeakSeen',
  description:
    "Terms governing PeakSeen's services, digital products, and interactive tools.",
};

export default function TermsOfServicePage() {
  return (
    <>
      {/* Hero */}
      <section className="bg-charcoal py-24 lg:py-32">
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <FadeInOnScroll>
            <h1 className="font-display text-5xl lg:text-7xl font-black tracking-[-0.03em] text-ivory leading-[1.0]">
              Terms of Service
            </h1>
          </FadeInOnScroll>
        </div>
      </section>

      {/* Content */}
      <Section>
        <div className="mx-auto max-w-prose">
          <FadeInOnScroll>
            <p className="text-sm text-grey-400 mb-8">
              Last updated: March 2026
            </p>

            <div className="space-y-10 text-grey-600 font-body text-base leading-relaxed">
              {/* Service description */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  1. Service Description
                </h2>
                <p>
                  PeakSeen is a brand and product studio that provides brand
                  strategy, identity design, website design, and digital product
                  services. Through our website at peakseen.com, we also offer
                  interactive tools (Brand Clarity Score, Brand Name Generator,
                  Colour Palette Generator), a free Brand Report service,
                  digital products available for purchase, and educational blog
                  content.
                </p>
                <p className="mt-3">
                  By accessing or using our website and services, you agree to
                  be bound by these Terms of Service. If you do not agree with
                  any part of these terms, please do not use our website or
                  services.
                </p>
              </div>

              {/* Digital products */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  2. Digital Products
                </h2>
                <p>
                  Digital products purchased through PeakSeen (including
                  templates, guides, and toolkits) are delivered electronically
                  and are subject to the following terms:
                </p>
                <ul className="list-disc pl-6 mt-3 space-y-2">
                  <li>
                    <strong>Non-refundable:</strong> Due to the digital nature of
                    these products, all sales are final. We do not offer refunds
                    once a product has been delivered and accessed. If you
                    experience a technical issue with a product, contact us and
                    we will resolve it promptly.
                  </li>
                  <li>
                    <strong>Personal commercial licence:</strong> Each purchase
                    grants you a personal commercial licence to use the product
                    for your own business or personal projects. You may not
                    resell, redistribute, sublicence, or share the product files
                    with third parties.
                  </li>
                  <li>
                    <strong>Delivery:</strong> Digital products are delivered via
                    email and/or download link provided by Lemon Squeezy
                    immediately after purchase. If you do not receive your
                    product within 24 hours, contact us at hello@peakseen.com.
                  </li>
                </ul>
              </div>

              {/* Intellectual property */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  3. Intellectual Property
                </h2>
                <p>
                  All content on this website, including text, graphics, logos,
                  images, design elements, code, tools, and digital products, is
                  the intellectual property of PeakSeen unless otherwise stated.
                  You may not reproduce, distribute, modify, or create
                  derivative works from any content on this site without our
                  prior written consent.
                </p>
                <p className="mt-3">
                  Content generated by our AI-powered tools (such as brand name
                  suggestions) is provided as creative inspiration. We do not
                  claim ownership of names or ideas generated through these
                  tools, but we also do not guarantee that generated names are
                  available for trademark registration. It is your
                  responsibility to conduct due diligence before using any
                  generated content commercially.
                </p>
              </div>

              {/* User-generated content */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  4. User-Generated Content
                </h2>
                <p>
                  When you submit information through our forms, tools, or other
                  interactive features, you grant PeakSeen a non-exclusive,
                  royalty-free licence to use that information solely for the
                  purpose of delivering the requested service (e.g., generating
                  your Brand Report, processing your contact submission, or
                  powering our tools).
                </p>
                <p className="mt-3">
                  We will never use your submitted content for marketing or
                  public display without your explicit permission.
                </p>
              </div>

              {/* Limitation of liability */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  5. Limitation of Liability
                </h2>
                <p>
                  PeakSeen provides its website, tools, and content on an
                  &quot;as is&quot; and &quot;as available&quot; basis. While we
                  strive to ensure accuracy and reliability, we make no
                  warranties, express or implied, regarding:
                </p>
                <ul className="list-disc pl-6 mt-3 space-y-2">
                  <li>
                    The accuracy, completeness, or suitability of any
                    information, advice, or recommendations provided through our
                    tools, reports, or content.
                  </li>
                  <li>
                    Uninterrupted or error-free access to our website and
                    services.
                  </li>
                  <li>
                    The results obtained from using our tools or implementing
                    our recommendations.
                  </li>
                </ul>
                <p className="mt-3">
                  To the maximum extent permitted by law, PeakSeen shall not be
                  liable for any indirect, incidental, special, consequential,
                  or punitive damages arising from your use of our website,
                  tools, products, or services.
                </p>
              </div>

              {/* Governing law */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  6. Governing Law
                </h2>
                <p>
                  These Terms of Service shall be governed by and construed in
                  accordance with the laws of the Federal Republic of Nigeria.
                  Any disputes arising from these terms or your use of our
                  services shall be subject to the exclusive jurisdiction of the
                  courts of the Federal Republic of Nigeria.
                </p>
              </div>

              {/* Changes to terms */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  7. Changes to These Terms
                </h2>
                <p>
                  We reserve the right to update these Terms of Service at any
                  time. Changes will be posted on this page with an updated
                  &quot;Last updated&quot; date. Your continued use of our
                  website after changes are posted constitutes your acceptance of
                  the revised terms.
                </p>
              </div>

              {/* Contact */}
              <div>
                <h2 className="font-display text-xl font-bold text-charcoal mb-4">
                  8. Contact
                </h2>
                <p>
                  If you have any questions about these Terms of Service, please
                  contact us at:
                </p>
                <p className="mt-3">
                  <strong>Email:</strong>{' '}
                  <a
                    href="mailto:hello@peakseen.com"
                    className="text-accent hover:underline"
                  >
                    hello@peakseen.com
                  </a>
                </p>
                <p className="mt-1">
                  <strong>Website:</strong>{' '}
                  <a
                    href="https://peakseen.com"
                    className="text-accent hover:underline"
                  >
                    peakseen.com
                  </a>
                </p>
              </div>
            </div>
          </FadeInOnScroll>
        </div>
      </Section>
    </>
  );
}
